### ISSUE TITLE
EXPATH00 Error found while processing repo.xml: err: XPTY0004

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-data-xml#4]
while deploying into exist

POST:
<query xmlns='http://exist.sourceforge.net/NS/exist'><text><![CDATA[repo:install-and-deploy("http://gawati.org/data","http://dl.gawati.org/dev/gawati-data-latest.xar")]]></text></query>

RESPONSE:
<?xml version="1.0" ?><exception><path>/db</path><message>experr:EXPATH00 Error found while processing repo.xml: err:XPTY0004 Invalid cardinality for variable $node-set. Expected one or more, got empty [at line 46, column 10, source: /home/xstdev/apps/existdata/expathrepo/gawati-data-1.12/post-install.xql]
In function:
	local:build-sort-index() [53:12:/home/xstdev/apps/existdata/expathrepo/gawati-data-1.12/post-install.xql] [at line 1, column 1, source: repo:install-and-deploy(&quot;http://gawati.org/data&quot;,&quot;http://dl.gawati.org/dev/gawati-data-latest.xar&quot;)]</message></exception>202

**Comment by kohsah** [comment]
@ccsmart we havent changed anything in gawati-data recently.  Did it occur earlier or only recently  ? 

Secondly that post-install script expects gawati-data-xml to be installed and data loaded ... so the order of installation is significant.

**Comment by ccsmart** [comment]
Apparently it was the recently changed installation sequence and missing demodata at the time of installation.
If it's easy to do, would be nice to add a check and error message.
